### ISSUE TITLE
Reading fixed length string dataset ignores charset

### ISSUE THREAD

**Issue by JCzogalla** [jamesmudd/jhdf#113]
**Describe the bug/missing feature**
When reading a dataset of type fixed length string(i.e. StringData), the charset is ignored and the bytes are always decoded as US_ASCII (DatasetReader l. 336). It seems that HDFView has the same problem.

**To Reproduce**
Use the attached file: [utf8-fixed-length.zip](https://github.com/jamesmudd/jhdf/files/3733175/utf8-fixed-length.zip)
HDFView and jhdf will both show broken characters instead of umlauts.

**Expected behaviour**
DatasetReader should take the string type's charset into account.

**Please complete the following information:**
- `jhdf` version: 0.4.8
- Java version: 1.8
- Stack trace/problem site: DatasetReader l. 336

**Additional context**
StringData knows its charset, and the call to the private method fillFixedLengthStringData (DatasetReader l. 134) could use it as a parameter.

**Comment by jamesmudd** [comment]
Reproduced the issue. Should be an easy fix....

**Comment by jamesmudd** [comment]
Think I have fixed this one. If you get chance give it a try and let me know.
