### ISSUE TITLE
Multidimensional fixed length string datasets only reads first "row"

### ISSUE THREAD

**Issue by JCzogalla** [jamesmudd/jhdf#132]
**Describe the bug**
When reading a multidimensional dataset of type fixed length string, the same buffer position is read again and again.

**To Reproduce**
When opening the file [multidim_string_datasest.zip](https://github.com/jamesmudd/jhdf/files/3831970/multidim_string_datasest.zip), the result is three arrays with the content ["a1"," a2"]. This seems to be the case because DatasetReader#fillFixedLengthStringData is called recursively with always the same buffer and manually setting the position to the i-th element.
HDFView can read this just fine.
![grafik](https://user-images.githubusercontent.com/35594017/68599445-dac76300-04a0-11ea-906e-20d20d993a72.png)

**Please complete the following information:**
- `jhdf` version: 0.5.0
- Java version: 1.8

**Additional context**
One probable fix to do this is to use subbuffers for each recursive call. 
The other would be to store the position before reading and go to the expected position after the reading was done, maybe like so:
```
for (int i = 0; i < dims[0]; i++) {
  int pos = buffer.position();
  ByteBuffer elementBuffer = Utils.createSubBuffer(buffer, stringLength);
  stringPaddingHandler.setBufferLimit(elementBuffer);
  Array.set(data, i, charset.decode(elementBuffer).toString());
  buffer.position(pos + stringLength);
}
```

**Comment by jamesmudd** [comment]
Thanks this was a bad one! Reproduced and the fix is easy, don't reposition the buffer at all. Will look to do a release with these string fixes soon.

**Comment by JCzogalla** [comment]
Glad we can help :)
