### ISSUE TITLE
Typo in Dataset.isVariableLentgh()

### ISSUE THREAD

**Issue by SimonGreenaway** [jamesmudd/jhdf#182]
**Describe the bug**
Typo in Dataset.isVariableLentgh()

**To Reproduce**
N/A

**Expected behaviour**
isVariableLength()

**Please complete the following information:**
N/A

**Additional context**

**Comment by jamesmudd** [comment]
Yes! Probably the word I typo the most! Very easy fix shame its on the API but think its reasonable to just change it. Open a PR if you want or I will get around to it soon.
