### ISSUE TITLE
Should support lzf compression. 

### ISSUE THREAD

**Issue by tyward** [jamesmudd/jhdf#239]
**What is the suggestion?**

Many .h5 files use lzf compression, which is not supported by the library, but easy to add. 

**How would it be an improvement?**

This would allow opening files that require lzf compression. 

**Additional context**

I have prepared a patch which provides the necessary support. It uses a pure java lzf compression library, and thus can easily be incorporated with a one line change to the gradle config, a one line change to the filter manager, and the new filter class, also included. 

[0001-Adding-LZF-support-to-jhdf.patch.zip](https://github.com/jamesmudd/jhdf/files/5656502/0001-Adding-LZF-support-to-jhdf.patch.zip)

**Comment by jamesmudd** [comment]
Thanks yes I agree adding LZF compression would be a good idea. The supplied patch looks great, would also need tests, so if you want to do that and open a PR let me know, otherwise I will take a look in the next few days.

**Comment by tyward** [comment]
Looks like I don't have permissions to push a branch to this repo, so I'm not able to produce a pull request here. Also, I'm actually not sure where to get an .h5 file that uses .lzf compression. The ones I have access to are all proprietary. 

If you can put this in over the next few days, that's great. If not, see if you can get me access to push a branch upstream to the repo, and then I'll try to add the test and make a proper PR for this.

**Comment by jamesmudd** [comment]
I have incorporated this patch and merged it here #240. I have made a new v0.5.11 release including this patch, so you should be able to use that version without issue. Thanks

**Comment by tyward** [comment]
Perfect, 

Thanks!

-Tyler
