### ISSUE TITLE
Create HdfFile object from InputStream without creating temp file

### ISSUE THREAD

**Issue by tooptoop4** [jamesmudd/jhdf#245]
I have hdf5 files on different sources, ie website, s3,etc. I have a java InputStream they are read into (could easily make a byte array or similar from them) but I want to create HdfFile object from that InputStream. I don't want to write out a local file for them.

I see fromInputStream is available but that will write out a temp file that hangs around till end of the application, but I have long running application that will be up for months at a time so I don't want the disk to be filled from reading many files.

Feature request is ability to create HdfFile object **without** creating temp/local file.

**Comment by jamesmudd** [comment]
How would you propose to random access the stream? This is the main issue to resolve? 

Or would you be happy for the full stream to be read into memory just not saved to disk?

Would a solution allowing the temp file to be removed without the application ending be acceptable?

**Comment by tooptoop4** [comment]
"Or would you be happy for the full stream to be read into memory just not saved to disk?" - yes. Rather than reading from inputstream, reading from a byte array would be fine.

**Comment by jamesmudd** [comment]
Made quite a bit of progress to implement this here https://github.com/jamesmudd/jhdf/pull/249 still needs a bit more tidy up but hopefully will be done soon.

**Comment by jamesmudd** [comment]
I have merged a fix for this #249 

It adds 2 new API methods `HdfFile#fromBytes(byte[] bytes)` and `HdfFile#fromByteBuffer(ByteBuffer byteBuffer)` which read hold the file in memory.

I hope to get around to making a release soon.

**Comment by jamesmudd** [comment]
Fixed in the https://github.com/jamesmudd/jhdf/releases/tag/v0.6.0 release
