### ISSUE TITLE
Add support for Committed Datatypes

### ISSUE THREAD

**Issue by jamesmudd** [jamesmudd/jhdf#255]
Currently reading a file containing Committed Datatypes causes an exception. Support needs to be added

**Comment by jamesmudd** [comment]
https://github.com/jamesmudd/jhdf/tree/datatype-support contains work towards this

**Comment by jamesmudd** [comment]
A test file containing committed datatypes and shared datatypes in attributes
[browsing.h5.zip](https://github.com/jamesmudd/jhdf/files/5976595/browsing.h5.zip)

**Comment by jamesmudd** [comment]
Fix for this merged here https://github.com/jamesmudd/jhdf/pull/256

**Comment by cgivre** [comment]
Thanks @jamesmudd for the fix!   Will you be building a new release that incorporates this fix?

**Comment by jamesmudd** [comment]
Yes have just released https://github.com/jamesmudd/jhdf/releases/tag/v0.6.1 give it a try and let me know if this is resolved. Thanks
