### ISSUE TITLE
Support for Multi dimension array data types

### ISSUE THREAD

**Issue by raedma** [jamesmudd/jhdf#341]
I don't quite know if this is a bug or a suggestion.

**What is the suggestion?**

I urgently need to read hdf5 file that seems to require a currently not supported feature. A `HdfException: Multi dimension array data types are not supported` is thrown. The error message does not mention which column of the compound dataset causes the problem, but I guess the array columns are the problem.

![image](https://user-images.githubusercontent.com/25957103/149346219-aa82d265-6ddd-45e4-9eed-a4e0b1e50767.png)

**How would it be an improvement?**

I can not change the source format. So support for this feature would be required for the application of `jhdf`  in my code and enriches the calatogue of supported features. If someone has an idea about the implementation, I would write the tests for my cases.

**Additional context**

- Example: [test_MultiDimensionArray.zip](https://github.com/jamesmudd/jhdf/files/7863412/test_MultiDimensionArray.zip)
- Code: (Same for DATASET1 & DATASET2)

      HdfFile hdf = new HdfFile(PATH);
      Node node = hdf.getByPath("GROUP1/GROUP2/DATASET1");
      NodeType type = node.getType();
      assert (type == NodeType.DATASET);
      Dataset dataset = (Dataset)node;
      Map<String,Object> data = (Map<String,Object>)dataset.getData();

- Log (thrown for the call of `getData()`):

      io.jhdf.exceptions.HdfException: Multi dimension array data types are not supported
        at io.jhdf.object.datatype.ArrayDataType.fillData(ArrayDataType.java:71)
        at io.jhdf.dataset.DatasetReader.readDataset(DatasetReader.java:64)
        at io.jhdf.dataset.CompoundDatasetReader.readDataset(CompoundDatasetReader.java:49)
        at io.jhdf.object.datatype.CompoundDataType.fillData(CompoundDataType.java:100)
        at io.jhdf.dataset.DatasetReader.readDataset(DatasetReader.java:64)
        at io.jhdf.dataset.DatasetBase.getData(DatasetBase.java:129)

- Environment:
  - jhdf version: 0.6.4
  - Java version: 13
  - OS: Windows

**Comment by jamesmudd** [comment]
Thanks for this. I think its a enhancement request., this has not been implemented yet. I will need to have a look but hopefully can outline how this could be implemented. Will you have time to work on the implementation?

**Comment by raedma** [comment]
I can most certainly try. However, I guess I lack the necessary skills ;) Would test though.

**Comment by jamesmudd** [comment]
There is a possible fix for this issue here https://github.com/jamesmudd/jhdf/pull/344 would be great if you could test it or maybe add a PR writing tests. Let me know if it works for you.

**Comment by raedma** [comment]
That did seem to do the trick. Thx. Added a PR with two tests.

**Comment by jamesmudd** [comment]
Merged https://github.com/jamesmudd/jhdf/pull/344 which fixes this issue

**Comment by jamesmudd** [comment]
I have released v0.6.5 which includes the fix for this issue

**Comment by raedma** [comment]
Thank you very much
