### ISSUE TITLE
Add Lz4 filter

### ISSUE THREAD

**Issue by Heiney-Upenn** [jamesmudd/jhdf#415]
Would it be possible to add an LZ4 filter?  My application using the jhdf library cannot open the attached file
[493aadda-5540-4597-81a8_1148_data_000001.h5.zip](https://github.com/jamesmudd/jhdf/files/9683594/493aadda-5540-4597-81a8_1148_data_000001.h5.zip)
which uses filter ID 32004 .

**Comment by jamesmudd** [comment]
For more info see https://support.hdfgroup.org/services/filters/HDF5_LZ4.pdf

**Comment by jamesmudd** [comment]
Possibly working jar still needs lots of testing and cleanup.
Remove `.zip` extension
[jhdf-0.6.8-lz4-beta.jar.zip](https://github.com/jamesmudd/jhdf/files/9700875/jhdf-0.6.8-lz4-beta.jar.zip)

**Comment by jamesmudd** [comment]
Merged https://github.com/jamesmudd/jhdf/pull/417
