### ISSUE TITLE
Support UTF-8 characters

### ISSUE THREAD

**Issue by tianxie** [jamesmudd/jhdf#539]
**What is the suggestion?**

I have UTF-8 characters in path. I cannot get node by path.

It would be great if jhdf can support UTF-8 characters.

![Snipaste_2024-02-02_14-52-55](https://github.com/jamesmudd/jhdf/assets/1201368/4ff1c0b1-5a12-469d-a4eb-2f096b31491c)

**Comment by jamesmudd** [comment]
Thanks a lot for trying jhdf and raising this issue. UTF8 should be supported in jhdf so maybe this is a bug getting datasets by path.

I will need to investigate. Do you have an example file which demonstrates this issue?

**Comment by tianxie** [comment]
Please check this file.

[new.zip](https://github.com/jamesmudd/jhdf/files/14137276/new.zip)

**Comment by jamesmudd** [comment]
I have reproduced and fixed this issue #544 

This will go in the next release, however that will add initial writing support and there is still quite a bit to do there so can't promise a time scale

**Comment by jamesmudd** [comment]
This is fixed in release v0.7.0
