### ISSUE TITLE
Group getChildren() returns wrong order of child nodes?!

### ISSUE THREAD

**Issue by raedma** [jamesmudd/jhdf#599]
**Describe the bug**

I do need to iterate over the subgroups of a `Group`. To do that I access the subgroups as children by `group.getChildren()`. This returns a `Map<String,Node>` with the keys being the child name and the `Node` being the child. For an example (see MWE below) I found that the order of the entries in the Map is not the same between the representation in HDFView and the result in `jhdf`. This causes me some problems for an example HDF5-file that I get from a colleague.

I tried reproducing the behavior with an own HDF5 file that I created by hand. There the problem did not occur.

I would expect both entry orders in the children map to be the same.

**To Reproduce**

Files: [resources.zip](https://github.com/user-attachments/files/16373968/resources.zip)

*** MWE that works as expected ***

I manually created the attached file `testOrderGroupChildren.h5"`. This looks like that in HDFView (3.1.3):

![image](https://github.com/user-attachments/assets/15713920-856c-4c6e-a380-80360ac8ad13)

 I wrote a small test to get the children of the `Group` *jmes*:
        
        HdfFile hdf = new HdfFile(new File("src/test/resources/testOrderGroupChildren.h5"));
        assertNotNull(hdf);
        
        Node jmes = hdf.getChild("jmes");
        assertNotNull(jmes);
        assertTrue(jmes instanceof Group);
        
        Group jmesImpl = (Group)jmes;
        
        Map<String, Node> children = jmesImpl.getChildren();
        
        System.out.println(children.keySet());

that prints: `[0, 1, 2, 3]` as expected

The same order appears in case of iterating over the entryset of the Map:

        for (Map.Entry<String,Node> entry : children.entrySet()){
            System.out.println("key: " + entry.getKey());
        }

gives

    key: 0
    key: 1
    key: 2
    key: 3

Log:

    [main] INFO io.jhdf.HdfFile - Opening HDF5 file '...\testOrderGroupChildren.h5'...
    [main] INFO io.jhdf.HdfFile - Opened HDF5 file '...\testOrderGroupChildren.h5'
    [main] INFO io.jhdf.GroupImpl - Lazy loading children of '//'
    [main] INFO io.jhdf.GroupImpl - Lazy loading children of '/jmes/'

*** MWE that does not work as expected ***

I stripped down the actual hdf5 file that couses problems into `testOrderGroupChildren2.h5"`. This looks like that in HDFView (3.1.3):

![image](https://github.com/user-attachments/assets/0819efab-6f4f-4814-b947-4f844b562887)

 I wrote a small test to get the children of the `Group` *VMAP/VARIABLES/STATE-0*:

        //
        HdfFile hdf = new HdfFile(new File("src/test/resources/testOrderGroupChildren2.h5"));
        assertNotNull(hdf);
        
        Node jmes = hdf.getByPath("VMAP/VARIABLES/STATE-0");
        assertNotNull(jmes);
        assertTrue(jmes instanceof Group);
        
        Group jmesImpl = (Group)jmes;
        
        Map<String, Node> children = jmesImpl.getChildren();
        
        System.out.println(children.keySet());

that prints: `[0, 2, 1, 3]`. Iterating over the entryset of the map gives

    key: 0
    key: 2
    key: 1
    key: 3

Here you see that the order diverges. Elements 2 and 1 are in reverse order. I would not expect that behavior.

Log:

    [main] INFO io.jhdf.HdfFile - jHDF version: 0.8.0
    [main] INFO io.jhdf.HdfFile - Opening HDF5 file '...\testOrderGroupChildren2.h5'...
    [main] INFO io.jhdf.HdfFile - Opened HDF5 file '...\testOrderGroupChildren2.h5'
    [main] INFO io.jhdf.GroupImpl - Lazy loading children of '//'
    [main] INFO io.jhdf.GroupImpl - Lazy loading children of '/VMAP/'
    [main] INFO io.jhdf.GroupImpl - Lazy loading children of '/VMAP/VARIABLES/'
    [main] INFO io.jhdf.GroupImpl - Lazy loading children of '/VMAP/VARIABLES/STATE-0/'

**Expected behaviour**

I would expect both examples to print `[0, 1, 2, 3]`

**Please complete the following information:**
- `jhdf` version: tested with 0.6.5 and 0.8.0 -> equal behavior
- Java version: 21
- OS: Windows
- Stack trace if available: No exception produced
- `jhdf` logging if available: See MWEs

**Comment by Apollo3zehn** [comment]
I am not sure about Java, but in many languages the keys of dictionaries / maps have no particular order. I also don't know how jHDF works internally but HDF5 format allows the storage of the groups creation order and maybe HDFView sorts based on this order while jHDF sorts by their appearance in the HDF5 internal b-tree.

**Comment by raedma** [comment]
@Apollo3zehn Thanks. Maybe the `keySet()` wasn't the best example as even if its a `LinkedHashSet` the order of the elements is not guaranteed, only the iteration over them always results in the same order. But if I iterate over the entryset of the `Map<String,Node>` end print the keys I also get the "wrong" order. I would expect the actual `Map` implementation that `getChildren()` uses to return something in the sorts of a `LinkedHashMap` where order is retained during iteration over the entries. Am I wrong here?

**Comment by jamesmudd** [comment]
Thanks for raising this issue. I will take a closer look at your example file. jHDF does not do anything special to sort the order of children in groups. So they will indeed be in the order they appear in the file. If this file has group creation order enabled, then maybe its a bug that they should be returned in that defined order. 

I suspect HDFView is just sorting alphabetically to make the view nicer to read in the UI. Would also be worth looking at the `h5dump` output to compare. Needs a little more investigation so will take a look.

**Comment by jamesmudd** [comment]
I have taken a look and reproduced this.

The order is indeed in the order they appear in the file e.g.
```
((Group) hdfFile.getByPath("VMAP/VARIABLES/STATE-0")).getChildren().values().stream().map(Node::getAddress).collect(Collectors.toList())
```
gives
```
[2328, 342432, 395184, 525744]
```

`h5dump` also sorts the group by name e.g. from the docs
```
Q - is the sort index type. It can be "creation_order" or "name" (default)
```
So I don't really think this is a bug.

If you want the order sorted you can put the children in sorted map e.g. a `TreeMap`
```
new TreeMap(((Group) hdfFile.getByPath("VMAP/VARIABLES/STATE-0")).getChildren())
```

**Comment by jamesmudd** [comment]
Going to close this as I don't think there is a bug here and have provided a workaround if you want sorting
