### ISSUE TITLE
Attributes with variable length strings are written incorrectly

### ISSUE THREAD

**Issue by jcschaff** [jamesmudd/jhdf#641]
**Describe the bug**

JHDF provides the ability to write attributes as arrays of Strings, there are a few tests in io.jhdf.writing.StringWritingTest for attributes with 1D and 2D arrays of Strings of fixed length.  This is essential for storing labels or units for a dataset.

However, writing an attribute with a 1-D array of strings where the strings are not the same length does not work correctly.  For example:
["vv", "xx", "abcdef"] is read-back as ["vv", "cdedf", ""]
["", "1", "mm2"] is read-back as ["", "m2", ""]

**To Reproduce**

	@Test
	@Order(3)
	void writeVarStringAttributes() throws Exception {
		Path tempFile = Files.createTempFile(this.getClass().getSimpleName(), ".hdf5");
		WritableHdfFile writableHdfFile = HdfFile.write(tempFile);

		// Write a dataset with string attributes
		WritiableDataset writiableDataset = writableHdfFile.putDataset("dataset", new double[] {0.1, 0.2, 0.3});
		writiableDataset.putAttribute("labels", new String[] {"vv", "xx", "abcdedf"});
		writiableDataset.putAttribute("units", new String[] {"", "1", "mm2"});
		writableHdfFile.close();

		// Now read it back
		try (HdfFile hdfFile = new HdfFile(tempFile)) {
			Dataset dataset = hdfFile.getDatasetByPath("dataset");

			// Expected :["vv", "xx", "abcdef"]
			// Actual   :["vv", "cdedf", ""]
			assertThat(dataset.getAttribute("labels").getData()).isEqualTo(new String[] {"vv", "xx", "abcdef"});

			// Expected :["", "1", "mm2"]
			// Actual   :["", "m2", ""]
			assertThat(dataset.getAttribute("units").getData()).isEqualTo(new String[] {"", "1", "mm2"});
		} finally {
			tempFile.toFile().delete();
		}
	}

**Expected behaviour**

The problem is in the writing not the reading, I verified that JHDF writes incorrectly be reading the dataset in HdfView.

**Please complete the following information:**
- `jhdf` version: 0.8.3
- Java version: 17
- OS (Windows, Mac, Linux): Mac M3

**Comment by jamesmudd** [comment]
Thanks for reporting this issue and providing a test. I will take a look as soon as I can.

**Comment by jcschaff** [comment]
Thank you very much for jhdf.  This simple, pure-Java HDF5 library has become strategic in our effort to simplify and modernize our large legacy project.  After looking quickly into jhdf, I didn't arrive at a clean solution strategy.  If the fix is not too involved, maybe you can advise me on an approach and I can submit a PR.

**Comment by jamesmudd** [comment]
PR for fix https://github.com/jamesmudd/jhdf/pull/642

**Comment by jcschaff** [comment]
Thank you very much, I tested this version locally and it works well for me.

**Comment by jamesmudd** [comment]
Fix released in v0.8.4 https://github.com/jamesmudd/jhdf/releases/tag/v0.8.4

**Comment by jcschaff** [comment]
Thanks for the quick turnaround on the fix and the release, very nice!
