### ISSUE TITLE
Add support for reference data type

### ISSUE THREAD

**Issue by exceeddata** [jamesmudd/jhdf#91]
Hi, I have a matlab v7.3 file, which is HDF5 based but it use reference data type which is currently not available in jhdf.  Can this be added?  I can provide the test files.

Thanks

**Comment by jamesmudd** [comment]
Reference data types could be supported. However this is currently not one of the highest priorities for me, and with relatively little time to spend on jhdf at the moment probably won't get done for a while. I you have time to spend on developing it I would be happy to help and would much appreciate the contribution.

If you could attach an example file that would be useful in the future for anyone looking at this issue.

**Comment by jamesmudd** [comment]
Changes have been made to support reference data types which are available in the `v0.4.8` release. Please give this try. If it doesn't work open a new issue detailing the problem.
